In [5]:
#Import Modules

# #GPyOpt - Cases are important, for some reason
# import GPyOpt
# from GPyOpt.methods import BayesianOptimization

#numpy
import numpy as np
from numpy.random import multivariate_normal #For later example

import pandas as pd

#Plotting tools
from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt
from matplotlib import cm
from matplotlib.ticker import LinearLocator, FormatStrFormatter
import numpy as np
from numpy.random import multivariate_normal

# # --- Load GPyOpt
# from GPyOpt.methods import BayesianOptimization
# %pylab inline
# import GPyOpt
# import GPy
import numpy as np
import pickle

In /home/akshartamal/anaconda3/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle: 
The text.latex.unicode rcparam was deprecated in Matplotlib 3.0 and will be removed in 3.2.
In /home/akshartamal/anaconda3/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle: 
The savefig.frameon rcparam was deprecated in Matplotlib 3.1 and will be removed in 3.3.
In /home/akshartamal/anaconda3/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle: 
The pgf.debug rcparam was deprecated in Matplotlib 3.0 and will be removed in 3.2.
In /home/akshartamal/anaconda3/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle: 
The verbose.level rcparam was deprecated in Matplotlib 3.1 and will be removed in 3.3.
In /home/akshartamal/anaconda3/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle: 
The verbose.fileo rcparam was deprecated in Matplotlib 3.1 and will be removed in 3.

In [103]:

def f(x):
    """
    x is a 4D vector.
    Function which will send alpha_1, alpha_2, alpha_3 and alpha_4 
    to the actual model and will get the dice coefficient in return.
    """
    print(x)
    alpha_1 = x[:, 0][0]
    alpha_2 = x[:, 1][0]
    alpha_3 = x[:, 2][0]
    alpha_4 = x[:, 3][0]
    print("--------",alpha_1," ",alpha_2," ",alpha_3," ",alpha_4)
    print(alpha_1+alpha_2+alpha_3+alpha_4)
    # Here we will send the alphas to the actual model and in return 
    # we will recieve the dice coefficient to optimise, since this is
    # a maximization problem, we return the -ve of objective function
    # to be maximized
    dice_coef = alpha_1 + alpha_2 + alpha_3 + alpha_4
    return -dice_coef
    

domain = [{'name': 'alpha_1', 'type': 'continuous', 'domain': (0,1), 'dimensionality':1},
          {'name': 'alpha_2', 'type': 'continuous', 'domain': (0,1), 'dimensionality':1},
          {'name': 'alpha_3', 'type': 'continuous', 'domain': (0,1), 'dimensionality':1},
          {'name': 'alpha_4', 'type': 'continuous', 'domain': (0,1), 'dimensionality':1}]

constraints = [{'name': 'constr_1', 'constraint': '0.9999 - x[:,0] - x[:,1] - x[:,2] - x[:,3]'},
               {'name': 'constr_1', 'constraint': '-1.00001 + x[:,0] + x[:,1] + x[:,2] + x[:,3]'}]

In [8]:
def load_entire_file_into_memory_and_then_convert(filename):
    with open(filename, 'r') as input_file:
        full_file_contents = input_file.read()
        lines_of_file = full_file_contents.split('\n')
        return np.array(lines_of_file)

In [9]:
dump = load_entire_file_into_memory_and_then_convert('bayesian_opt.txt')
dump

array(['0.08 0.21 0.41 0.29 0.8204611565826954 0.7294653047374877 0.5984979476118675 ',
       '0.29 0.05 0.54 0.11 0.8072160317661081 0.7155189802126833 0.5775783918606147 ',
       '0.29 0.0 0.01 0.69 0.812904026950075 0.7167761088267817 0.5826701852868961 ',
       '0.74 0.11 0.06 0.09 0.8100668303113453 0.7124475283110303 0.5771301110220688 ',
       '0.71 0.11 0.12 0.05 0.8104434808833403 0.7125621277941039 0.5774913311950931 ',
       '0.53 0.06 0.3 0.1 0.8108956103898957 0.715345636662372 0.5800706366810827 ',
       '0.0 0.45 0.42 0.12 0.8206900487797066 0.7299970391456998 0.5991013056655258 ',
       '0.13 0.21 0.57 0.08 0.8091234585961964 0.7204843376780048 0.5829607791664171 ',
       '0.62 0.01 0.24 0.12 0.8076005842559397 0.7082406354839689 0.5719755510106513 ',
       '0.09 0.22 0.37 0.31 0.8099462899218561 0.7205992058774199 0.583646653321052 ',
       '0.09 0.16 0.43 0.31 0.8100357922720149 0.720253083004172 0.5834307767276458 ',
       '0.28 0.09 0.41 0.21 0.8086312020

In [10]:
X = []
Y = []
for item in dump[:-1]:
    all_items = item.split(' ')
    X.append([float(i) for i in all_items[:4]]) 
    Y.append(float(all_items[-2]))
    

In [12]:
X = np.array(X)
X

array([[0.08, 0.21, 0.41, 0.29],
       [0.29, 0.05, 0.54, 0.11],
       [0.29, 0.  , 0.01, 0.69],
       [0.74, 0.11, 0.06, 0.09],
       [0.71, 0.11, 0.12, 0.05],
       [0.53, 0.06, 0.3 , 0.1 ],
       [0.  , 0.45, 0.42, 0.12],
       [0.13, 0.21, 0.57, 0.08],
       [0.62, 0.01, 0.24, 0.12],
       [0.09, 0.22, 0.37, 0.31],
       [0.09, 0.16, 0.43, 0.31],
       [0.28, 0.09, 0.41, 0.21],
       [0.1 , 0.  , 0.44, 0.45],
       [0.04, 0.02, 0.54, 0.39],
       [0.19, 0.42, 0.31, 0.08],
       [0.19, 0.12, 0.6 , 0.09],
       [0.  , 0.64, 0.1 , 0.25],
       [0.4 , 0.3 , 0.08, 0.21],
       [0.22, 0.37, 0.16, 0.24],
       [0.52, 0.19, 0.24, 0.04],
       [0.25, 0.  , 0.62, 0.12],
       [0.14, 0.5 , 0.07, 0.28],
       [0.41, 0.21, 0.35, 0.02],
       [0.06, 0.54, 0.27, 0.12],
       [0.09, 0.05, 0.13, 0.72],
       [0.08, 0.32, 0.22, 0.37],
       [0.31, 0.59, 0.02, 0.07],
       [0.1 , 0.73, 0.08, 0.08],
       [0.78, 0.08, 0.05, 0.08],
       [0.  , 0.52, 0.32, 0.15],
       [0.

In [13]:
X.shape

(53, 4)

In [15]:
Y = -np.array(Y)
Y

array([-0.59849795, -0.57757839, -0.58267019, -0.57713011, -0.57749133,
       -0.58007064, -0.59910131, -0.58296078, -0.57197555, -0.58364665,
       -0.58343078, -0.58054887, -0.59637313, -0.56699331, -0.60953861,
       -0.57881295, -0.60030423, -0.60174646, -0.61712525, -0.58669302,
       -0.58717204, -0.58914312, -0.61028212, -0.60687508, -0.58118995,
       -0.60495712, -0.57948106, -0.6023255 , -0.5668431 , -0.59330768,
       -0.57767926, -0.59078254, -0.60185259, -0.60602386, -0.5646971 ,
       -0.57906603, -0.58987934, -0.58360822, -0.5904794 , -0.59749917,
       -0.59534472, -0.6073189 , -0.58946552, -0.60514409, -0.59967922,
       -0.5910062 , -0.59455611, -0.58266668, -0.570847  , -0.58559178,
       -0.60209525, -0.5740414 , -0.5768926 ])

In [112]:
Y.shape

(20, 1)

In [111]:
Y = np.expand_dims(Y, axis=1)
Y

array([[-0.95914031],
       [-0.96172594],
       [-0.96035367],
       [-0.95743563],
       [-0.96022589],
       [-0.94106186],
       [-0.96340175],
       [-0.96285481],
       [-0.96225729],
       [-0.95858635],
       [-0.96095901],
       [-0.95977781],
       [-0.9400788 ],
       [-0.94105916],
       [-0.96109757],
       [-0.95762963],
       [-0.95864002],
       [-0.9576237 ],
       [-0.95691875],
       [-0.95802394]])

In [ ]:
Y.shape

In [113]:
maxiter = 1

kernel = GPy.kern.Matern52(input_dim=4, ARD=True, variance=1, lengthscale=[1,1,1,1]);

myBopt_4d = GPyOpt.methods.BayesianOptimization(f=f, X=X, Y=Y, domain=domain, constraints = constraints,
                                                kernel=kernel, acquisition_type ='EI', model_type='GP', 
                                                verbosity=True, acquisition_optimizer_type='lbfgs', 
                                                cost_withGradients=None, exact_feval=True)

myBopt_4d.run_optimization(max_iter = maxiter, verbosity=True)
print("="*20)
print("Value of (x,y) that minimises the objective:"+str(myBopt_4d.x_opt))    
print("Minimum value of the objective: "+str(myBopt_4d.fx_opt))     
print("="*20)
#myBopt_4d.plot_acquisition()

[[0.23070297 0.00674209 0.39912914 0.36343547]]
-------- 0.23070296550728328   0.006742091006239273   0.39912914455401327   0.36343547111957786
1.0000096721871137
num acquisition: 1, time elapsed: 139.79s
Value of (x,y) that minimises the objective:[0.23070297 0.00674209 0.39912914 0.36343547]
Minimum value of the objective: -1.0000096721871137


In [88]:
myBopt_4d.X.shape

(6, 4)

In [86]:
myBopt_4d.Y

array([[-0.99990714],
       [-0.99998241],
       [-0.99992333],
       [-0.99994381],
       [-1.00000402],
       [-0.99999817]])