In [1]:
import numpy as np, numpy.random
import pickle

In [54]:
# Generating Cases
alpha_datas = []
i = 0
while i <= 80:
    alphas = np.random.dirichlet(np.ones(4),size=1)
    
    print("case = ", i+1, " ", float("%0.2f" % (alphas[0][0])), 
          float("%0.2f" % (alphas[0][1])), float("%0.2f" % (alphas[0][2])), float("%0.2f" % (alphas[0][3])))
    if float("%0.2f" % (alphas[0][0]))+float("%0.2f" % (alphas[0][1]))+float("%0.2f" % (alphas[0][2]))+float("%0.2f" % (alphas[0][3])) >= 1.0000000000000000000000001:
        i -= 1
        print("--"*40, "skipped")
        print(float("%0.2f" % (alphas[0][0]))+float("%0.2f" % (alphas[0][1]))+float("%0.2f" % (alphas[0][2]))+float("%0.2f" % (alphas[0][3])))
        continue
    alpha_datas.append(alphas)
    print("--",len(alpha_datas))
    i += 1
    if len(alpha_datas) > 80: 
        break
    print(float("%0.2f" % (alphas[0][0]))+float("%0.2f" % (alphas[0][1]))+float("%0.2f" % (alphas[0][2]))+float("%0.2f" % (alphas[0][3])))

case =  1   0.27 0.3 0.18 0.25
-------------------------------------------------------------------------------- skipped
1.0
case =  0   0.28 0.1 0.33 0.29
-------------------------------------------------------------------------------- skipped
1.0
case =  -1   0.17 0.16 0.23 0.44
-------------------------------------------------------------------------------- skipped
1.0
case =  -2   0.23 0.13 0.26 0.38
-------------------------------------------------------------------------------- skipped
1.0
case =  -3   0.08 0.21 0.41 0.29
-- 1
0.99
case =  -2   0.36 0.31 0.16 0.18
-------------------------------------------------------------------------------- skipped
1.01
case =  -3   0.15 0.18 0.36 0.31
-------------------------------------------------------------------------------- skipped
1.0
case =  -4   0.05 0.63 0.21 0.12
-------------------------------------------------------------------------------- skipped
1.01
case =  -5   0.41 0.11 0.47 0.02
--------------------------------------------

-------------------------------------------------------------------------------- skipped
1.0
case =  -180   0.0 0.92 0.02 0.06
-------------------------------------------------------------------------------- skipped
1.0
case =  -181   0.57 0.26 0.1 0.07
-------------------------------------------------------------------------------- skipped
1.0
case =  -182   0.17 0.01 0.37 0.44
-- 54
0.99
case =  -181   0.38 0.32 0.25 0.05
-------------------------------------------------------------------------------- skipped
1.0
case =  -182   0.29 0.16 0.26 0.28
-- 55
0.99
case =  -181   0.02 0.06 0.7 0.22
-- 56
0.9999999999999999
case =  -180   0.19 0.02 0.12 0.67
-------------------------------------------------------------------------------- skipped
1.0
case =  -181   0.08 0.16 0.23 0.53
-------------------------------------------------------------------------------- skipped
1.0
case =  -182   0.43 0.21 0.21 0.16
-------------------------------------------------------------------------------- sk

In [55]:
# inp => alpha_1, alpha_2, alpha_3 and alpha_4 to the function 
# the function will return dice coef values, and we need to find 
# the alphas which maximizes the dice coef values.

In [56]:
alpha_datas

[array([[0.08426291, 0.21029283, 0.41424587, 0.29119839]]),
 array([[0.29018319, 0.05415561, 0.54461868, 0.11104251]]),
 array([[0.29367191, 0.00471388, 0.00850293, 0.69311128]]),
 array([[0.74051881, 0.11028642, 0.05762829, 0.09156648]]),
 array([[0.71469587, 0.11297986, 0.12183238, 0.05049189]]),
 array([[0.52845532, 0.06274144, 0.30396822, 0.10483502]]),
 array([[0.00293575, 0.45492201, 0.42076901, 0.12137323]]),
 array([[0.1343499 , 0.21339449, 0.57314334, 0.07911227]]),
 array([[0.62165112, 0.01459503, 0.24191407, 0.12183979]]),
 array([[0.09388169, 0.22357257, 0.37073794, 0.3118078 ]]),
 array([[0.09321057, 0.1630467 , 0.43266845, 0.31107428]]),
 array([[0.28371876, 0.09142003, 0.41455446, 0.21030675]]),
 array([[0.10176847, 0.00385994, 0.44243451, 0.45193708]]),
 array([[0.04433641, 0.02072309, 0.54191646, 0.39302404]]),
 array([[0.18801269, 0.42490944, 0.30667124, 0.08040663]]),
 array([[0.19373581, 0.11915062, 0.59885726, 0.0882563 ]]),
 array([[0.00372119, 0.64259279, 0.09969

In [57]:
len(alpha_datas[:80])

80

In [58]:

with open('alpha_datas.pickle', 'wb') as handle:
    pickle.dump(alpha_datas[:80], handle, protocol=pickle.HIGHEST_PROTOCOL)

with open('alpha_datas.pickle', 'rb') as handle:
    b = pickle.load(handle)


In [59]:
print(b)
print(len(b))

[array([[0.08426291, 0.21029283, 0.41424587, 0.29119839]]), array([[0.29018319, 0.05415561, 0.54461868, 0.11104251]]), array([[0.29367191, 0.00471388, 0.00850293, 0.69311128]]), array([[0.74051881, 0.11028642, 0.05762829, 0.09156648]]), array([[0.71469587, 0.11297986, 0.12183238, 0.05049189]]), array([[0.52845532, 0.06274144, 0.30396822, 0.10483502]]), array([[0.00293575, 0.45492201, 0.42076901, 0.12137323]]), array([[0.1343499 , 0.21339449, 0.57314334, 0.07911227]]), array([[0.62165112, 0.01459503, 0.24191407, 0.12183979]]), array([[0.09388169, 0.22357257, 0.37073794, 0.3118078 ]]), array([[0.09321057, 0.1630467 , 0.43266845, 0.31107428]]), array([[0.28371876, 0.09142003, 0.41455446, 0.21030675]]), array([[0.10176847, 0.00385994, 0.44243451, 0.45193708]]), array([[0.04433641, 0.02072309, 0.54191646, 0.39302404]]), array([[0.18801269, 0.42490944, 0.30667124, 0.08040663]]), array([[0.19373581, 0.11915062, 0.59885726, 0.0882563 ]]), array([[0.00372119, 0.64259279, 0.09969194, 0.25399408]

In [60]:
for item in b:
    print(item[0][0]+item[0][1]+item[0][2]+item[0][3])

1.0000000000000002
1.0
1.0
1.0
1.0
1.0
0.9999999999999999
0.9999999999999998
1.0
0.9999999999999999
0.9999999999999998
0.9999999999999999
1.0
1.0
1.0000000000000002
1.0
0.9999999999999998
1.0000000000000002
1.0
1.0
1.0
0.9999999999999999
0.9999999999999998
1.0
0.9999999999999999
1.0
1.0000000000000002
1.0
0.9999999999999998
1.0000000000000002
1.0
1.0
1.0000000000000002
1.0
1.0
0.9999999999999998
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
0.9999999999999998
1.0
1.0
1.0
1.0
0.9999999999999999
1.0000000000000002
1.0000000000000002
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
0.9999999999999999
1.0
1.0
0.9999999999999998
0.9999999999999998
0.9999999999999999
1.0000000000000002
0.9999999999999998
1.0
1.0
1.0000000000000002
1.0
0.9999999999999999
1.0000000000000002
1.0000000000000002
1.0
0.9999999999999998
0.9999999999999998
