In [11]:
import numpy as np, numpy.random
import pickle

In [3]:
# Generating Cases
alpha_datas = []
for i in range(20):
    alphas = np.random.dirichlet(np.ones(4),size=1)
    alpha_datas.append(alphas)
    print("case = ", i+1, " ", float("%0.2f" % (alphas[0][0])), 
          float("%0.2f" % (alphas[0][1])), float("%0.2f" % (alphas[0][2])), float("%0.2f" % (alphas[0][3])))
    print(float("%0.2f" % (alphas[0][0]))+float("%0.2f" % (alphas[0][1]))+float("%0.2f" % (alphas[0][2]))+float("%0.2f" % (alphas[0][3])))

case =  1   0.4 0.24 0.08 0.29
1.01
case =  2   0.37 0.47 0.15 0.01
1.0
case =  3   0.42 0.02 0.12 0.44
1.0
case =  4   0.31 0.2 0.18 0.31
1.0
case =  5   0.56 0.18 0.17 0.09
1.0
case =  6   0.31 0.53 0.08 0.09
1.01
case =  7   0.14 0.09 0.01 0.76
1.0
case =  8   0.38 0.49 0.1 0.04
1.01
case =  9   0.34 0.43 0.11 0.11
0.99
case =  10   0.17 0.08 0.24 0.51
1.0
case =  11   0.01 0.59 0.38 0.02
1.0
case =  12   0.47 0.02 0.47 0.03
0.99
case =  13   0.04 0.06 0.13 0.77
1.0
case =  14   0.32 0.04 0.51 0.13
1.0
case =  15   0.11 0.09 0.03 0.76
0.99
case =  16   0.37 0.28 0.0 0.35
1.0
case =  17   0.28 0.15 0.13 0.45
1.01
case =  18   0.2 0.1 0.02 0.68
1.0
case =  19   0.06 0.15 0.41 0.37
0.99
case =  20   0.18 0.64 0.13 0.05
1.0


In [ ]:
# inp => alpha_1, alpha_2, alpha_3 and alpha_4 to the function 
# the function will return dice coef values, and we need to find 
# the alphas which maximizes the dice coef values.

In [9]:
alpha_datas

[array([[0.39891469, 0.23577671, 0.07564421, 0.28966438]]),
 array([[0.36878121, 0.47341166, 0.14817254, 0.00963458]]),
 array([[0.42246312, 0.0224608 , 0.11758933, 0.43748676]]),
 array([[0.31341021, 0.20044301, 0.17961627, 0.30653051]]),
 array([[0.5570836 , 0.18162502, 0.16668195, 0.09460943]]),
 array([[0.30656411, 0.53031091, 0.07780486, 0.08532012]]),
 array([[0.13835468, 0.08963897, 0.0144104 , 0.75759595]]),
 array([[0.3759122 , 0.48788657, 0.09700522, 0.039196  ]]),
 array([[0.33842613, 0.43365869, 0.11443579, 0.11347938]]),
 array([[0.16998547, 0.08050855, 0.24309576, 0.50641023]]),
 array([[0.01050173, 0.5944783 , 0.37905571, 0.01596426]]),
 array([[0.47338145, 0.02454448, 0.47402381, 0.02805027]]),
 array([[0.03991346, 0.05932248, 0.13488015, 0.76588391]]),
 array([[0.32363558, 0.03908431, 0.50548237, 0.13179774]]),
 array([[0.1142189 , 0.08858075, 0.03318612, 0.76401422]]),
 array([[0.36758272, 0.28230737, 0.0004801 , 0.34962981]]),
 array([[0.28038329, 0.14695279, 0.12677

In [12]:

with open('alpha_datas.pickle', 'wb') as handle:
    pickle.dump(alpha_datas, handle, protocol=pickle.HIGHEST_PROTOCOL)

with open('alpha_datas.pickle', 'rb') as handle:
    b = pickle.load(handle)


[array([[0.39891469, 0.23577671, 0.07564421, 0.28966438]]),
 array([[0.36878121, 0.47341166, 0.14817254, 0.00963458]]),
 array([[0.42246312, 0.0224608 , 0.11758933, 0.43748676]]),
 array([[0.31341021, 0.20044301, 0.17961627, 0.30653051]]),
 array([[0.5570836 , 0.18162502, 0.16668195, 0.09460943]]),
 array([[0.30656411, 0.53031091, 0.07780486, 0.08532012]]),
 array([[0.13835468, 0.08963897, 0.0144104 , 0.75759595]]),
 array([[0.3759122 , 0.48788657, 0.09700522, 0.039196  ]]),
 array([[0.33842613, 0.43365869, 0.11443579, 0.11347938]]),
 array([[0.16998547, 0.08050855, 0.24309576, 0.50641023]]),
 array([[0.01050173, 0.5944783 , 0.37905571, 0.01596426]]),
 array([[0.47338145, 0.02454448, 0.47402381, 0.02805027]]),
 array([[0.03991346, 0.05932248, 0.13488015, 0.76588391]]),
 array([[0.32363558, 0.03908431, 0.50548237, 0.13179774]]),
 array([[0.1142189 , 0.08858075, 0.03318612, 0.76401422]]),
 array([[0.36758272, 0.28230737, 0.0004801 , 0.34962981]]),
 array([[0.28038329, 0.14695279, 0.12677