In [2]:
import numpy as np, numpy.random
import pickle

In [27]:
# Generating Cases
alpha_datas = []
i = 0
while i <= 20:
    alphas = np.random.dirichlet(np.ones(4),size=1)
    
    print("case = ", i+1, " ", float("%0.2f" % (alphas[0][0])), 
          float("%0.2f" % (alphas[0][1])), float("%0.2f" % (alphas[0][2])), float("%0.2f" % (alphas[0][3])))
    if float("%0.2f" % (alphas[0][0]))+float("%0.2f" % (alphas[0][1]))+float("%0.2f" % (alphas[0][2]))+float("%0.2f" % (alphas[0][3])) >= 1.0000000000000000000000001:
        i -= 1
        print("--"*40, "skipped")
        print(float("%0.2f" % (alphas[0][0]))+float("%0.2f" % (alphas[0][1]))+float("%0.2f" % (alphas[0][2]))+float("%0.2f" % (alphas[0][3])))
        continue
    alpha_datas.append(alphas)
    print("--",len(alpha_datas))
    i += 1
    if len(alpha_datas) > 20: 
        break
    print(float("%0.2f" % (alphas[0][0]))+float("%0.2f" % (alphas[0][1]))+float("%0.2f" % (alphas[0][2]))+float("%0.2f" % (alphas[0][3])))

case =  1   0.24 0.42 0.31 0.03
-------------------------------------------------------------------------------- skipped
1.0
case =  0   0.11 0.33 0.12 0.44
-------------------------------------------------------------------------------- skipped
1.0
case =  -1   0.3 0.23 0.04 0.44
-------------------------------------------------------------------------------- skipped
1.01
case =  -2   0.01 0.17 0.43 0.38
-- 1
0.99
case =  -1   0.03 0.54 0.03 0.39
-- 2
0.9900000000000001
case =  0   0.42 0.49 0.07 0.02
-------------------------------------------------------------------------------- skipped
1.0
case =  -1   0.27 0.0 0.36 0.37
-------------------------------------------------------------------------------- skipped
1.0
case =  -2   0.28 0.32 0.28 0.13
-------------------------------------------------------------------------------- skipped
1.0100000000000002
case =  -3   0.08 0.36 0.33 0.22
-- 3
0.99
case =  -2   0.21 0.09 0.54 0.16
---------------------------------------------------------

In [ ]:
# inp => alpha_1, alpha_2, alpha_3 and alpha_4 to the function 
# the function will return dice coef values, and we need to find 
# the alphas which maximizes the dice coef values.

In [28]:
alpha_datas

[array([[0.01497121, 0.17214525, 0.43247156, 0.38041198]]),
 array([[0.03441565, 0.54495779, 0.03484588, 0.38578068]]),
 array([[0.08099579, 0.36397756, 0.3323976 , 0.22262905]]),
 array([[0.30376777, 0.14299276, 0.26411446, 0.28912501]]),
 array([[0.56213356, 0.25315923, 0.07214955, 0.11255766]]),
 array([[0.40210891, 0.09321507, 0.10365529, 0.40102073]]),
 array([[0.07498378, 0.1520144 , 0.53281453, 0.2401873 ]]),
 array([[0.57210608, 0.01336275, 0.17484666, 0.23968451]]),
 array([[0.3532656 , 0.28441805, 0.05386436, 0.308452  ]]),
 array([[0.50457958, 0.12437113, 0.30746685, 0.06358244]]),
 array([[0.47319637, 0.0760715 , 0.22867837, 0.22205376]]),
 array([[0.65277084, 0.07421512, 0.04485663, 0.22815742]]),
 array([[0.23448595, 0.10944052, 0.40459451, 0.25147903]]),
 array([[0.03463893, 0.36162068, 0.24157337, 0.36216702]]),
 array([[0.22427341, 0.30272715, 0.32802832, 0.14497112]]),
 array([[0.46553298, 0.13390803, 0.29445776, 0.10610123]]),
 array([[0.05825297, 0.59696726, 0.22442

In [29]:
len(alpha_datas[:20])

20

In [30]:

with open('alpha_datas.pickle', 'wb') as handle:
    pickle.dump(alpha_datas[:20], handle, protocol=pickle.HIGHEST_PROTOCOL)

with open('alpha_datas.pickle', 'rb') as handle:
    b = pickle.load(handle)


In [31]:
print(b)
print(len(b))

[array([[0.01497121, 0.17214525, 0.43247156, 0.38041198]]), array([[0.03441565, 0.54495779, 0.03484588, 0.38578068]]), array([[0.08099579, 0.36397756, 0.3323976 , 0.22262905]]), array([[0.30376777, 0.14299276, 0.26411446, 0.28912501]]), array([[0.56213356, 0.25315923, 0.07214955, 0.11255766]]), array([[0.40210891, 0.09321507, 0.10365529, 0.40102073]]), array([[0.07498378, 0.1520144 , 0.53281453, 0.2401873 ]]), array([[0.57210608, 0.01336275, 0.17484666, 0.23968451]]), array([[0.3532656 , 0.28441805, 0.05386436, 0.308452  ]]), array([[0.50457958, 0.12437113, 0.30746685, 0.06358244]]), array([[0.47319637, 0.0760715 , 0.22867837, 0.22205376]]), array([[0.65277084, 0.07421512, 0.04485663, 0.22815742]]), array([[0.23448595, 0.10944052, 0.40459451, 0.25147903]]), array([[0.03463893, 0.36162068, 0.24157337, 0.36216702]]), array([[0.22427341, 0.30272715, 0.32802832, 0.14497112]]), array([[0.46553298, 0.13390803, 0.29445776, 0.10610123]]), array([[0.05825297, 0.59696726, 0.2244221 , 0.12035767]

In [32]:
for item in b:
    print(item[0][0]+item[0][1]+item[0][2]+item[0][3])

1.0
1.0
1.0
1.0
1.0
1.0
0.9999999999999999
0.9999999999999999
1.0
1.0
0.9999999999999999
1.0
1.0000000000000002
1.0
1.0
1.0000000000000002
1.0
0.9999999999999999
0.9999999999999999
1.0
